# Location: mixview/docker-compose.yml
# Description: Fixed Docker Compose configuration with proper networking and health checks

version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mixview_backend
    env_file: .env
    ports:
      - "8001:8001"  # Host:Container - Frontend will connect to localhost:8001
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mixview-network
    environment:
      - DATABASE_URL=postgresql://mixview:mixviewpass@db:5432/mixview
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mixview_frontend
    ports:
      - "3001:3001"  # Frontend runs on 3000 inside container, exposed on 3001
    environment:
      # Use the host machine's localhost for browser access
      - VITE_BACKEND_URL=http://backend:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mixview-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: mixview_db
    environment:
      POSTGRES_USER: mixview
      POSTGRES_PASSWORD: mixviewpass
      POSTGRES_DB: mixview
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mixview-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mixview -d mixview"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  pgdata:

networks:
  mixview-network:
    driver: bridge
