# Location: mixview/docker-compose.yml
# Description: Fixed Docker Compose configuration with proper networking

version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mixview_backend
    env_file: .env
    ports:
      - "8001:8001"  # Fixed: Map port 8001 to 8001
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - mixview-network
    environment:
      - DATABASE_URL=postgresql://mixview:mixviewpass@db:5432/mixview

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mixview_frontend
    ports:
      - "3001:3000"  # Frontend runs on 3000 inside container, exposed on 3001
    environment:
      # Use the host machine's localhost for browser access
      - VITE_BACKEND_URL=http://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mixview-network
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: mixview_db
    environment:
      POSTGRES_USER: mixview
      POSTGRES_PASSWORD: mixviewpass
      POSTGRES_DB: mixview
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mixview-network

volumes:
  pgdata:

networks:
  mixview-network:
    driver: bridge